import { join } from "node:path";
import { readFile } from "node:fs/promises";
import { sessionFiles, writeTask, type TaskFile } from "../ledger/index.js";
import type { SessionConfig, TranscriptEvent, TurnContext } from "../types/index.js";
import type { SeatRunner } from "./engine.js";

export interface DecomposeOpts {
  session: { dir: string; config: SessionConfig };
  /** A capable model that turns the spec into tasks. */
  planner: SeatRunner;
  now?: () => Date;
  onEvent?: (e: TranscriptEvent) => void;
  signal?: AbortSignal;
}

const INSTRUCTIONS =
  "Break the plan into 1–5 small, independently-implementable tasks. Respond with ONLY a JSON array, " +
  "no prose, in this shape:\n" +
  `[{"title": "...", "acceptance": ["shell command that verifies this task"], "owned_paths": ["dir/or/file"]}]\n` +
  "Each acceptance command must be runnable and deterministic (exit 0 = pass). Prefer a test or a build " +
  "command. If you cannot give a command, use an empty acceptance array.";

/** Extract a JSON array of tasks from a model response (tolerant of code fences / surrounding prose). */
export function parseTasksJson(text: string): Array<{ title: string; acceptance: string[]; owned_paths: string[] }> {
  const start = text.indexOf("[");
  const end = text.lastIndexOf("]");
  if (start < 0 || end <= start) return [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(text.slice(start, end + 1));
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];
  return parsed
    .filter((t): t is Record<string, unknown> => typeof t === "object" && t !== null && typeof (t as { title?: unknown }).title === "string")
    .map((t) => ({
      title: String(t["title"]),
      acceptance: Array.isArray(t["acceptance"]) ? t["acceptance"].filter((a): a is string => typeof a === "string") : [],
      owned_paths: Array.isArray(t["owned_paths"]) ? t["owned_paths"].filter((p): p is string => typeof p === "string") : [],
    }));
}

/**
 * Turn the converged plan (spec.md) into runtime task files (DESIGN §13). Acceptance commands are
 * written with the `$ ` prefix the acceptance runner recognizes. Returns the created tasks.
 */
export async function decomposePlan(opts: DecomposeOpts): Promise<TaskFile[]> {
  const { dir } = opts.session;
  const now = opts.now ?? (() => new Date());
  const [goal, spec] = await Promise.all([
    readFile(sessionFiles.goal(dir), "utf8").catch(() => ""),
    readFile(sessionFiles.spec(dir), "utf8").catch(() => ""),
  ]);

  const ctx: TurnContext = {
    seat: "planner",
    role: "arbiter",
    stage: "plan",
    turnInStage: 1,
    goal: goal.trim(),
    summary: "",
    recentTurns: [],
    pendingInjections: [],
    roleInstructions: `${INSTRUCTIONS}\n\nThe plan (spec.md):\n${spec.trim()}`,
  };

  const result = await opts.planner.takeTurn(ctx, opts.signal ?? new AbortController().signal);
  const specs = result.status === "ok" ? parseTasksJson(result.content) : [];

  const created: TaskFile[] = [];
  for (let i = 0; i < specs.length; i++) {
    const id = String(i + 1).padStart(3, "0");
    const task: TaskFile = {
      frontmatter: {
        id,
        title: specs[i]!.title,
        status: "todo",
        owned_paths: specs[i]!.owned_paths,
        acceptance: specs[i]!.acceptance.map((c) => `$ ${c}`),
      },
      body: "## Journal\n- (generated by decompose)\n",
    };
    await writeTask(join(sessionFiles.tasksDir(dir), `${id}.md`), task);
    created.push(task);
  }
  opts.onEvent?.({ ts: now().toISOString(), type: "control", action: "converged", by: "system", detail: `decomposed into ${created.length} tasks` });
  return created;
}
